FROM node:12-alpine
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build
ENV NODE_ENV=development
ENV JWT_SECRET=upstock#8310103202#satya!
EXPOSE 8080
CMD ["npm", "run", "start:prod"]